[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
clap = { version = "4.4.8", features = ["derive"] }
nom = "7.1.3"
num-traits = "0.2.17"

